import fs from 'fs';

// Normal
const normalTitles = [
  "Mumbai Street Style Pav Bhaji",
  "Fluffy Gujarati Dhokla",
  "Crispy Jalebi",
  "Gajar Halwa (Carrot Halwa)",
  "Spicy Chicken Tikka Masala",
  "South Indian Restaurant Style Prawn Curry",
  "Creamy Kheer (Rice Pudding)",
  "Best Indian Chaat",
  "Spicy Street Chana Chaat",
  "Upma",
  "South Indian Egg Masala",
  "Thandai",
  "Flaky Lachha Paratha",
  "Vegetable Biryani",
  "Aloo Gobi",
  "Kadhi Pakora",
  "Instant Idli Sambar",
  "Authentic Undhiyu Casserole",
  "Uttapam",
  "Kulfi (Indian Ice Cream)",
  "Nimbu Pani (Shikanji)",
  "Sweet Lassi",
  "South Indian Curd Rice",
  "Idiyappam (String Hoppers)",
  "Medu Vada",
  "Goan Fish Curry",
  "South Indian Filter Coffee",
  "Bhel Puri",
  "Dal Makhani",
  "Indian Masala Chai",
  "Perfect Jeera Rice",
  "Appam (Kerala Rice Pancakes)",
  "Kulcha",
  "Poori Masala",
  "Milk Barfi",
  "Samosa",
  "Chicken Fried Rice",
  "Authentic Chana Masala",
  "Garlic Naan",
  "Kerala Puttu",
  "Homemade Garlic Butter Naan",
  "Bhindi Masala",
  "Indian Cuisine Platter",
  "Besan Ladoo",
  "Tamarind Rice (Puliyodharai)",
  "Indian Chicken Korma",
  "Palak Paneer",
  "Coconut Chutney",
  "Sarson Ka Saag",
  "Pakora",
  "South Indian Uttapam",
  "Chicken Curry Paste",
  "Butter Chicken",
  "Pani Puri (Golgappa)",
  "Baingan Bharta",
  "Chicken 65",
  "South Indian Lemon Rice",
  "Mixed Vegetable Curry",
  "Aloo Tikki",
  "Rasgulla",
  "Aloo Paratha",
  "Ragda Pattice Chaat",
  "Indian Chicken Biryani",
  "Tandoori Chicken",
  "Indian Fish Fry",
  "Rajma (Kidney Beans Curry)",
  "Gulab Jamun",
  "Mutton Rogan Josh",
  "Homemade Fish Curry",
  "Sevpuri",
  "Punjabi Mutton Curry",
  "North Indian Breakfast Poha",
  "Rava Dosa",
  "Dal Tadka",
  "Roti (Chapati)",
  "Kadai Paneer Gravy",
  "Mutton Keema Curry",
  "Rasmalai",
  "Malai Kofta",
  "South Indian Rasam",
  "South Indian Vegetable Kurma",
  "Vegetarian Momo",
  "Maharashtrian Misal Pav",
  "Shahi Paneer Curry",
  "Chicken Chettinad",
  "South Indian Restaurant Egg Curry",
  "Chole Bhature",
  "Indian Chicken Biryani", // duplicate
  "Kaju Katli",
  "Khasta Kachori",
  "Sambar",
  "Paneer Butter Masala",
  "Butter Naan",
  "Veg Pulao",
  "South Indian Masala Dosa"
];

const counts = {};
normalTitles.forEach(t => {
  counts[t] = (counts[t] || 0) + 1;
});

console.log("Normal duplicate counts:");
Object.entries(counts).forEach(([t, c]) => {
  if (c > 1) {
    console.log(`  "${t}": ${c}`);
  }
});
